CREATE TABLE CLIENT_USER (
    ID INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(50),
    ACCESS_TOKEN VARCHAR(100) NULL,
    ACCESS_TOKEN_VALIDITY DATETIME NULL,
    REFRESH_TOKEN VARCHAR(100) NULL);